### ISSUE TITLE
why we need to read DB at page load of PromotionForm ? 

### ISSUE THREAD

**Issue by jLeta** [ETH-WORKS-DASHBOARD/HN_HR_1.0#4]
something like: 

    protected void Page_Load(object sender, EventArgs e)
    {
        string fName = null;
       //... DB access codes ...
    }

I don't understand why we need this. thank you for clarifying or remove it if not necessary.

**Comment by Jdan116** [comment]
the reason we read DB on this page is to get Which user is logged in into the system. Actual what we need here is First Name only. So that display the message "Welcome Daniel!" If i am the one logged in.

**Comment by Jdan116** [comment]
the reason we read DB on this page is to get Which user is logged in into the system. Actual what we need here is First Name only. So that we can display the message "Welcome Daniel!" If i am the one logged in.

**Comment by jLeta** [comment]
this has to be done in the Master page, not on each page.

**Comment by Jdan116** [comment]
I think this issue has been solved right?

**Comment by jLeta** [comment]
OK, then I close it, dont forget issue when they get solved.

**Comment by Jdan116** [comment]
i have never closed the Issue that is why  :P

**Comment by jLeta** [comment]
lol. know you know how to close issues

**Comment by Jdan116** [comment]
😬😉😉😂 Nop. Oooh wait let me ask Google :P

How Close Issue on Github Close Issue
<https://help.github.com/articles/closing-issues-via-commit-messages/>
